### PR TITLE
Issue #11: dockerized application with docker-compose and made travis running docker service for testing the app

### PR DESCRIPTION
**Pull request by olisikh**
Let's discuss when you have time. Alrighty?

### CODE REVIEW

**Comment by olisikh** [comment]
So, everything works fine, just the default docker-machine is mapped to 192.168.99.100, so after running `docker-compose up` you can access the application on http://192.168.99.100:8081/hello to see 'Hello world!'.

1. To run docker-compose build, you need to install docker on your machine. https://store.docker.com/search?type=edition&offering=community, here's a link for installation package. Please make sure you mark a checkbox for Virtualbox tools installation, we'll use it in favour of Hyper-V virtualization. Please make sure you don't enable Hyper-V on your machine, otherwise there might be conflicts.

2. Once you've installed Docker on your machine and completed all needed restarts, you can run `Docker quickstart terminal` from your desktop and go to `cd /path/to/project`. After that you can run the app by invoking `docker-compose up`

3. You should be able to access the app via `http://192.168.99.100/hello` from your browser after the docker fully starts up. Also mysql database is accessible via 3307 port. You can use Workbench to connect to it, the password for root user is the same.

In intellij IDEA you need to install Docker Integration plugin for better Docker support. This will allow you to run Docker containers from Intellij IDEA and monitor them, logs, environment variables and other will be available from IDEA.

**Comment by olisikh** [comment]
This task is still not finished, we need to create an additional docker-compose-test.yml for testing where we override CMD from Dockerfile with command: entry in docker-compose.yml. And run this docker-compose.yml on travis.

IDEA: maybe just change the CMD command in Dockerfile to:
first do the testing and then create an executable image with default spring-boot profile.

`mvn clean flyway:migrate test -Pdocker && mvn clean package -DskipTests`

Maybe after this we could publish an image to docker repository and have a runnable image tagged with a timestamp when the build was run

ALSO configure flyway fully via properties, according to this class:
https://github.com/flyway/flyway/blob/02c088737ab53f9a3b8965a9e7725a06c79a2c6a/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L1264

**Comment by olisikh** [comment]
If not objections, we can review and merge it for now. Later on, I'll try to speed-up the build, so that the .m2 dir is cached by travis between the builds.

**Review by artemlisikh — DISMISSED** [review]
That's a brilliant piece of work you've done, mate!

**Comment by olisikh** [comment]
awwww (:

**Review by artemlisikh — APPROVED** [review]

**Pull request merged**
